services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres-db
    restart: always
    environment:
      - 'POSTGRES_DB=mediscreen'
      - 'POSTGRES_PASSWORD=prajapati'
      - 'POSTGRES_USER=yogi'
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=yogi
      - MONGO_INITDB_ROOT_PASSWORD=prajapati
      - MONGO_INITDB_DATABASE=medical_notes
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  pgdata:
  mongo-data: